# Generated by Django 5.2.17 on 2026-09-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("hecha", models.BooleanField(default=False)),
                ("creada", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creada"],
            },
        ),
    ]
